# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

files: 'content/ADR-[0-9]+-.*\.md|[content|public]/resources/.*/.*\.md'
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
